### ISSUE TITLE
support paypal and other payment options

### ISSUE THREAD

**Issue by ldkingvivi** [TeamUbersmith/order-forms#6]
Hi,

Right now the order form already support credit card, is there a way to add other payment options, I know the UB build-in order form actually has it, but this open source one doesn't have it right now

**Comment by ubersmith** [comment]
## You're correct that the order forms expect credit cards as payment but they can be modified to accept whatever payment you'd like.  In the backend you'll need to look for the 'payment_type' variable that is being set in the order in Ubersmith.  You can change that to pass whatever value you may need.  You'll need to then adapt the form itself to take in whatever additional information the client may need to provide but once submitted to Ubersmith it should be able to process it in the standard fashion.

-boo van alstyne
ubersmith vp support

To view this ticket online, log in to https://billing.ubersmith.com/ticket.php?ticket_id=307401

**Comment by ldkingvivi** [comment]
Hi Boo,

Thanks for the info, is there a way you can give us some examples or point the right direction about how to add paypal to that, since that's a little bit different than the normal way for credit card, it will need to redirect the customer to the paypal site, and redirect back when they done with the paypal

**Comment by ubersmith** [comment]
## If you specify info[payment_type]='paypal' in the order details, when the call is made to the order.submit API function, the output that it returns will include the html form details needed to forward the client to paypal to finish their payment.  All you should really need to do is update the form to capture that output and send it to the client's browser.  The one thing you'll need to tweak in it is the return url value so that it sends the client back to the page you want them to come back to.

-boo van alstyne
ubersmith vp support

To view this ticket online, log in to https://billing.ubersmith.com/ticket.php?ticket_id=307401
